def guess_draw(guess)
  case guess
  when 1
    puts "  ____________"
    puts "  |          |"
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 2
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 3
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |          |"
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 4
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |          |"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 5
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 6
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 7
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/"
    puts "  |          |"
    puts "  |         / "
    puts "__|\\____________"
    puts "\n"
  when 8
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/"
    puts "  |          |"
    puts "  |         / \\ "
    puts "__|\\____________"
    puts "\n"
  else
    puts "  ____________"
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  end
end
